mercari/hcledit

cmd/hcledit/internal/command/create.go
cmd/hcledit/internal/command/root.go
cmd/hcledit/internal/command/update.go
cmd/hcledit/internal/command/update_test.go

Adds the `--type` flag same as the `create` command to the `update` command.

Support --type flag in update command

---

.github/workflows/lint.yml
.github/workflows/test.yml
hcledit.go
hcledit_test.go

This PR adds a `CustomEdit` function to allow custom functions to be run on the file, to support more detailed edits.
There are cases where the existing functions do not support the required use case. This includes cases where there's identical provider blocks and we only want to modify one. To support future use cases as well where this may be an issue, I went with a custom function approach. This will require users to know more low level details, but this is meant for more advanced use cases anyway. As such, this will not be added to the CLI tool.

add customedit function

---

hcledit_test.go
internal/handler/block.go
internal/handler/handler.go

title
If we're automatically generating HCL, we likely want to leave comments on generated blocks to let readers know the block was automatically generated. This adds this functionality.

[hcledit/create] add comments to block handler

---

cmd/hcledit/internal/command/fixture/file.tf
cmd/hcledit/internal/command/read.go
cmd/hcledit/internal/command/read_test.go
hcledit.go
hcledit_test.go
internal/handler/read.go
option.go

Currently this package always passes a `nil` `EvalContext` when evaluating HCL expressions. This means any value that references other attributes will fail to parse. This PR adds a fallback in this case to return the raw, un-evaluated value.
There's a couple reasons why this is useful:
1. In the case where the HCL file is referencing the output of a module, we'll never be able to correctly evaluate the final value without looking at the Terraform state. In cases like this, it makes sense to return the un-evaluated value since this CLI does not read any TF state or allow a way to input substitutions for `EvalContext`.
2. This module currently doesn't allow for users to programatically provide any `EvalContext` when executing a read operation. When working with and writing HCL files …

[hcledit/read] fallback to raw values if unparsable

---

hcledit_test.go
internal/handler/block.go

title
Currently, this appends the comment to the line prior to the new block, which is not what we want. The previous behavior would result in:
```hcl
prev {
} // comment
block "new block" {
}
```
This fixes this to do:
```hcl
prev {
}
// comment
block "new block" {
}
```

[hcledit/create] add new line before appending a block level comment

---

.goreleaser.yml

title
Goreleaser workflow is broken because `archives.replacements` is no longer valid. This should fix the automated releases I think 🤔

[goreleaser] add name template

---

.goreleaser.yml

title
The YAML was previously invalid 🤔 
Since we're using a multiline string with `>-`, we need to make sure we're not at the same indentation level that YAML expects another key

[goreleaser] fix indentation for name_template

---

.goreleaser.yml

Fix .goreleaser.yml.
goreleaser outputs warning.
These settings were deprecated.
```console
$ goreleaser release --snapshot
• DEPRECATED:  brews.folder  should not be used anymore, check https://goreleaser.com/deprecations#brewsfolder for more info
• DEPRECATED:  brews.tap  should not be used anymore, check https://goreleaser.com/deprecations#brewstap for more info
```
- https://goreleaser.com/deprecations/#brewstap
- https://goreleaser.com/deprecations/#brewsfolder

chore(goreleaser): fix deprecation warning

---

.github/workflows/release.yml

As the title suggests.
This PR is intended to fix the release workflow.
One of the causes for the release workflow not working properly can be attributed to the way of specifying the go version in `actions/setup-go`.
This is noted in the README of `actions/setup-go` as follows:
> The recommendation is based on the YAML parser's behavior, which interprets non-wrapped values as numbers and, in the case of version 1.20, trims it down to 1.2, which may not be very obvious.
https://github.com/actions/setup-go/blob/4ab57d7ea2fd0c9948210b2e0784e280674e7144/README.md?plain=1#L69-L75
You can confirm that `Go@v1.2.x` is installed from these logs.
```sh
Run actions/setup-go@v4
with: …
```

fix(cicd/release): single quotes around go-version in `actions/setup-go@v4`

---

.goreleaser.yml

Set `CGO_ENABLED=0` when building hcledit.
https://medium.com/@pengcheng1222/exploring-cgo-enabled-in-go-23cf5cf2fe88
To resolve the issue.
```
6_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by hcledit)
hcledit: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by hcledit)
```
Currently, hcledit depends on libc so hcledit doesn't work without libc.
By setting `CGO_ENABLED=0` when building hcledit, hcledit works without libc.

chore: set CGO_ENABLED=0

---

.github/workflows/docker.yml

This will catch if any changes break the build process. This is inspired because dependenabot auto-merged a change that broke the build process because there was no CI check on PRs to ensure build continues to work.
Actual fix for the build is in https://github.com/mercari/hcledit/pull/120

[ci/workflows] run `docker build` on PRs

---

.github/workflows/docker.yml

title
repo secrets are not available on `pull_request` events and this is not needed since we do not push the image for PR builds

[ci/workflows] skip docker login for PR builds

---

.github/workflows/release.yml
.goreleaser.yml

Currently `goreleaser` is attempting to push directly to trunk which is blocked by our different rulesets. Instead, we can have `goreleaser` open a PR and that can be merged manually so that we have no exceptions for all changes being made through a PR.
https://github.com/mercari/hcledit/issues/113

[workflows/release] have `goreleaser` open PRs to update tap

---

hcledit.go
hcledit_test.go
internal/query/query.go
option.go
option_test.go

title 
Terraform allows comma-separated attributes (e.g. aliased providers like google.common inside a module). In order to modify attributes with comma in its name, we need a way to specify the queryStr split separator charactor.
given: 
```
module "A" {
providers = {
google.aliasA = google.aliasA
}
}
```
where:
```
hcledit.Create("module.A.providers.google.aliasB", RawVal("google.aliasB"))
```
then:
```
module "A" {
providers = {
google.aliasA = google.aliasA
}
}
```
Because queryStr considers all the commas as the query separator.
target:
```
module "A" {
providers = {
google.aliasA = google.aliasA
google.aliasB = google.aliasB
}
}
```

[feat] add an option for queryStr separator

---

.github/workflows/release.yml
.goreleaser.yml

The `pull_request` key should be nested under `repository`.

[goreleaser] fix tap config

---

hcledit_test.go
internal/handler/block.go
internal/handler/handler.go

title 
`Hcledit.Create` with `BlockVal` ignores the WithNewLine option. This PR fixes that.

[feat]: BlockVal should reflects WithNewLine option

---

.goreleaser.yml

I think this is the cause for 404 error when `goreleaser` attempts to find the default branch.

[goreleaser] specify the main branch

---

.github/workflows/release.yml

I believe this is the last permission needed to allow `goreleaser` to upload the artifacts needed to create a release.
This PR should fix this error message found in this workflow run: https://github.com/mercari/hcledit/actions/runs/10054218246/job/27788393692
```
⨯ release failed after 1m8s                error=scm releases: failed to publish artifacts: failed to upload hcledit_0.0.15_Linux_x86_64.tar.gz after 1 tries: POST https://uploads.github.com/repos/mercari/hcledit/releases/166614281/assets?name=hcledit_0.0.15_Linux_x86_64.tar.gz: 422 Validation Failed [{Resource:ReleaseAsset Field:name Code:already_exists Message:}]
```

[goreleaser] add `packages: write` permissions

---

hcledit_test.go
internal/handler/read.go

If fallback option is enabled, add parsed value to results even if there is an error (in objects)
At the moment, the fallback option doesn't work for object attributes

Fallback to raw values in object attributes

---

.goreleaser.yml

This property defaults to the repo's default branch which is causing goreleaser to attempt to merge directly to `main`. Setting this property to another branch name should hopefully allow it to create a PR and successfully update the tap.

[goreleaser] specify branch name for PR
